docker_auth: &docker_auth
  username: ((registry-username))
  password: ((registry-password))

resources:
# The repo with our Dockerfile
- name: jenkins-git
  type: git
  icon: github
  source:
    uri: https://github.com/nikwebbons/docker-testing
    branch: main

#Where we will push the image to
- name: jenkins-base
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-base

- name: jenkins-scala
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-scala

- name: jenkins-cloud-foundry-cli
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-cloud-foundry-cli

- name: jenkins-node
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-node

- name: jenkins-python
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-python

- name: jenkins-gradle
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-python

- name: jenkins-gmu
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-gmu

- name: jenkins-maven
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-maven

- name: jenkins-sbt
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-sbt

- name: jq
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jq

- name: cm
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/cm

jobs:
- name: jenkins-base
  plan:
  - get: jenkins-git
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/jenkins-base
      run:
        path: build
  - put: jenkins-base
    params:
      image: image/image.tar
      version: 1.0.0

- name: jenkins-scala-2.11.8
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2.11.8
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2.11.8

- name: jenkins-scala-2.12.7
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2.12.7
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2.12.7

- name: jenkins-sbt-1.2.4
  plan:
  - get: jenkins-git
    passed: [jenkins-scala-2.12.7]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/sbt
        BUILD_ARG_TOOL_VERSION: 1.2.4
        BUILD_ARG_MAJOR_MINOR_VERSION: 1.1
        BUILD_ARG_TOOL_DEPENDENCY_VERSION: 2.12.7
      run:
        path: build
  - put: jenkins-sbt
    params:
      image: image/image.tar
      version: 1.2.4

- name: jenkins-scala-2-13-4
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2-13-4
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2-13-4

- name: jenkins-cloud-foundry-cli
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/cloud-foundry
      run:
        path: build
  - put: jenkins-cloud-foundry-cli
    params:
      image: image/image.tar
      version: 1.0.0

- name: jenkins-node-6.11.5
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v6.11.5
        BUILD_ARG_SHA256: fffd25c9e9b6d2235e97ba8be1dd6ea5f31e32ea445c5cc704ca84ef44db66c1
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 6.11.5

- name: jenkins-node-9.9.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v9.9.0
        BUILD_ARG_SHA256: 887cb4db6207f303b5ba15b6e15298f19d288fce2064e8caa7bb7cae170cbe85
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 9.9.0

- name: jenkins-node-12.16.2
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v12.16.2
        BUILD_ARG_SHA256: ffc92b8d9f53a10a2a734c93e78a3be74af7b0034bddd6f034a700c430eb94c1
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 12.16.2

- name: jenkins-node-15.3.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v15.3.0
        BUILD_ARG_SHA256: c3f6c64d98e623c783b7de7580365be74d8a2dba87529447ae66061609b5d0ec
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 15.3.0

- name: jenkins-python-2.7.15
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v2.7.15
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 2.7.15

- name: jenkins-python-3.6.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.6.0
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.6.0

- name: jenkins-python-3.6.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.6.1
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.6.1

- name: jenkins-python-3.8.7
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.8.7
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.8.7

- name: jenkins-python-3.9.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.9.1
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.9.1

- name: jenkins-gradle-4.9
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/gradle
        BUILD_ARG_TOOL_VERSION: 4.9
      run:
        path: build
  - put: jenkins-gradle
    params:
      image: image/image.tar
      version: 4.9

- name: jenkins-gmu
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/gmu
      run:
        path: build
  - put: jenkins-gmu
    params:
      image: image/image.tar
      version: latest

- name: jenkins-maven-3.5.4
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/gmu
        BUILD_ARG_TOOL_VERSION: 3.5.4
        BUILD_ARG_SHA256: ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d
        BUILD_ARG_SHA512: 2a803f578f341e164f6753e410413d16ab60fabe31dc491d1fe35c984a5cce696bc71f57757d4538fe7738be04065a216f3ebad4ef7e0ce1bb4c51bc36d6be86
      run:
        path: build
  - put: jenkins-maven
    params:
      image: image/image.tar
      version: 3.5.4

- name: jenkins-maven-3.6.3
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/gmu
        BUILD_ARG_TOOL_VERSION: 3.6.3
        BUILD_ARG_SHA512: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
      run:
        path: build
  - put: jenkins-maven
    params:
      image: image/image.tar
      version: 3.6.3

- name: jenkins-jq-1.6
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/jq
        BUILD_ARG_TOOL_VERSION: 1.6
      run:
        path: build
  - put: jenkins-jq
    params:
      image: image/image.tar
      version: 1.6

- name: jenkins-cm-1.0
  plan:
  - get: jenkins-git
    passed: [jenkins-node-12.16.2]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/cm
        BUILD_ARG_TOOL_VERSION: 4.0.1
        BUILD_ARG_PARENT_VERSION: 12.16.2
      run:
        path: build
  - put: jenkins-cm
    params:
      image: image/image.tar
      version: 1.0.0

- name: jenkins-cm-2.0
  plan:
  - get: jenkins-git
    passed: [jenkins-node-15.3.0]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/cm
        BUILD_ARG_TOOL_VERSION: 4.0.1
        BUILD_ARG_PARENT_VERSION: 15.3.0
      run:
        path: build
  - put: jenkins-cm
    params:
      image: image/image.tar
      version: 2.0.0
