docker_auth: &docker_auth
  username: ((registry-username))
  password: ((registry-password))

resources:
# The repo with our Dockerfile
- name: jenkins-git
  type: git
  icon: github
  source:
    uri: https://github.com/nikwebbons/docker-testing
    branch: main

#Where we will push the image to
- name: jenkins-base
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-base

- name: jenkins-scala
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-scala

- name: jenkins-cloud-foundry-cli
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-cloud-foundry-cli

- name: jenkins-node
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-node

- name: jenkins-python
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-python

- name: jenkins-gradle
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: spydernik/jenkins-python

jobs:
- name: jenkins-base
  plan:
  - get: jenkins-git
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/jenkins-base
      run:
        path: build
  - put: jenkins-base
    params:
      image: image/image.tar
      version: 1.0.0

- name: jenkins-scala-2.11.8
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2.11.8
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2.11.8

- name: jenkins-scala-2.12.7
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2.12.7
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2.12.7

- name: jenkins-scala-2-13-4
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/scala
        BUILD_ARG_TOOL_VERSION: 2-13-4
      run:
        path: build
  - put: jenkins-scala
    params:
      image: image/image.tar
      version: 2-13-4

- name: jenkins-cloud-foundry-cli
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/cloud-foundry
      run:
        path: build
  - put: jenkins-cloud-foundry-cli
    params:
      image: image/image.tar
      version: 1.0.0

- name: jenkins-node-6.11.5
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v6.11.5
        BUILD_ARG_SHA256: fffd25c9e9b6d2235e97ba8be1dd6ea5f31e32ea445c5cc704ca84ef44db66c1
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 6.11.5

- name: jenkins-node-9.9.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v9.9.0
        BUILD_ARG_SHA256: 887cb4db6207f303b5ba15b6e15298f19d288fce2064e8caa7bb7cae170cbe85
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 9.9.0

- name: jenkins-node-12.16.2
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v12.16.2
        BUILD_ARG_SHA256: ffc92b8d9f53a10a2a734c93e78a3be74af7b0034bddd6f034a700c430eb94c1
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 12.16.2

- name: jenkins-node-15.3.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/node
        BUILD_ARG_TOOL_VERSION: v15.3.0
        BUILD_ARG_SHA256: c3f6c64d98e623c783b7de7580365be74d8a2dba87529447ae66061609b5d0ec
      run:
        path: build
  - put: jenkins-node
    params:
      image: image/image.tar
      version: 15.3.0

- name: jenkins-python-2.7.15
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v2.7.15
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 2.7.15

- name: jenkins-python-3.6.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.6.0
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.6.0

- name: jenkins-python-3.6.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.6.1
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.6.1

- name: jenkins-python-3.8.7
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.8.7
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.8.7

- name: jenkins-python-3.9.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/python
        BUILD_ARG_TOOL_VERSION: v3.9.1
      run:
        path: build
  - put: jenkins-python
    params:
      image: image/image.tar
      version: 3.9.1

- name: jenkins-gradle-4.9
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: jenkins-git
      outputs:
      - name: image
      params:
        CONTEXT: jenkins-git/gradle
        BUILD_ARG_TOOL_VERSION: 4.9
      run:
        path: build
  - put: jenkins-gradle
    params:
      image: image/image.tar
      version: 4.9
